# Generated by Django 5.1.3 on 2024-11-20 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=150)),
                ('Description', models.TextField(max_length=2000, null=True)),
                ('Image', models.ImageField(default='cat_images/default.jpg', upload_to='cat_images')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('Titre', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Creer_le', models.DateTimeField(auto_now=True)),
                ('Image_formation', models.ImageField(default='default.jpg', upload_to='formationimages')),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.categorie')),
                ('Createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('Titre', models.TextField()),
                ('video_id', models.CharField(max_length=11)),
                ('Contenu', models.TextField()),
                ('position', models.IntegerField()),
                ('formation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.formation')),
            ],
        ),
    ]
