# Generated by Django 3.0.4 on 2020-03-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200315_0959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.RenameField(
            model_name='Categorie',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='Categorie',
            old_name='short_description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='Categorie',
            old_name='title',
            new_name='Titre',
        ),
    ]
