# Generated by Django 5.1.3 on 2024-11-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200315_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='Description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='Image',
            field=models.ImageField(default='cat_images/default.jpg', upload_to='cat_images'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.formation'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(max_length=11),
        ),
    ]
